In [1]:
import pandas as pd
def load_data(file_path: str) -> pd.DataFrame:
    """
    Load data from a CSV file into a pandas DataFrame.

    Parameters:
    file_path (str): The path to the CSV file.

    Returns:
    pd.DataFrame: A DataFrame containing the loaded data.
    """
    try:
        data = pd.read_csv(file_path)
        return data
    except Exception as e:
        print(f"An error occurred while loading the data: {e}")
        return pd.DataFrame()  # Return an empty DataFrame on error

In [2]:
Ob_data=load_data("BTC_1min.csv")
Ob_data

,Unnamed: 0,system_time,midpoint,spread,buys,sells,bids_distance_0,bids_distance_1,bids_distance_2,bids_distance_3,...,asks_market_notional_5,asks_market_notional_6,asks_market_notional_7,asks_market_notional_8,asks_market_notional_9,asks_market_notional_10,asks_market_notional_11,asks_market_notional_12,asks_market_notional_13,asks_market_notional_14
0,0,2021-04-07 11:33:41.122161+00:00,55896.285,0.01,4.448599e+06,3.899402e+06,-8.945138e-08,-0.000065,-0.000073,-0.000154,...,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,1176.72998,0.0
1,1,2021-04-07 11:34:41.122161+00:00,55948.685,1.43,1.243244e+06,3.606502e+06,-1.277957e-05,-0.000013,-0.000242,-0.000242,...,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.00000,0.0
2,2,2021-04-07 11:35:41.122161+00:00,56013.785,0.01,3.069094e+06,1.575759e+06,-8.926374e-08,-0.000009,-0.000070,-0.000088,...,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.00000,0.0
3,3,2021-04-07 11:36:41.122161+00:00,55903.575,7.17,1.220819e+06,1.321487e+06,-6.412827e-05,-0.000182,-0.000188,-0.000225,...,0.000000,312.040009,0.0,0.0,0.0,0.0,0.0,0.0,0.00000,0.0
4,4,2021-04-07 11:37:41.122161+00:00,55899.995,0.01,2.011287e+06,3.083005e+06,-8.944544e-08,-0.000129,-0.000130,-0.000143,...,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.00000,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17108,17108,2021-04-19 09:50:00.386544+00:00,56878.090,6.54,7.205687e+04,1.542092e+05,-5.749138e-05,-0.000058,-0.000068,-0.000094,...,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.00000,0.0
17109,17109,2021-04-19 09:51:00.386544+00:00,56944.085,2.57,9.383907e+04,3.085079e+04,-2.256600e-05,-0.000028,-0.000088,-0.000093,...,549.880005,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.00000,0.0
17110,17110,2021-04-19 09:52:00.386544+00:00,56873.165,0.01,3.366408e+05,1.198253e+05,-8.791493e-08,-0.000069,-0.000128,-0.000189,...,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.00000,0.0
17111,17111,2021-04-19 09:53:00.386544+00:00,56820.445,0.01,3.118859e+04,8.355952e+04,-8.799650e-08,-0.000039,-0.000088,-0.000113,...,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.00000,0.0
17112,17112,2021-04-19 09:54:00.386544+00:00,56862.695,2.03,1.471420e+05,4.964134e+04,-1.785002e-05,-0.000030,-0.000119,-0.000136,...,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.00000,0.0

In [3]:
trading_data=load_data("BTCUSD_1m_Combined_Index.csv")
trading_data

,Open time,Volume,Open,High,Low,Close
0,2011-08-18 12:37:00,0.489908,10.90,10.90,10.90,10.90
1,2011-08-18 12:38:00,0.000000,10.90,10.90,10.90,10.90
2,2011-08-18 12:39:00,0.000000,10.90,10.90,10.90,10.90
3,2011-08-18 12:40:00,0.000000,10.90,10.90,10.90,10.90
4,2011-08-18 12:41:00,0.000000,10.90,10.90,10.90,10.90
...,...,...,...,...,...,...
7246356,2025-05-28 17:13:00,126838.281480,107724.30,107780.40,107721.89,107769.97
7246357,2025-05-28 17:14:00,458533.324113,107769.97,107770.00,107670.30,107670.40
7246358,2025-05-28 17:15:00,295620.940394,107670.40,107689.51,107609.10,107648.51
7246359,2025-05-28 17:16:00,164516.353234,107648.51,107757.90,107641.41,107754.30
7246360,2025-05-28 17:17:00,222803.399635,107754.30,107760.10,107740.70,107742.30

In [4]:
trading_data['Open time'] = pd.to_datetime(trading_data['Open time'])
Ob_data['system_time'] = pd.to_datetime(Ob_data['system_time'])
Ob_data['system_time'] = Ob_data['system_time'].dt.tz_localize(None)

In [5]:

trading_data

,Open time,Volume,Open,High,Low,Close
0,2011-08-18 12:37:00,0.489908,10.90,10.90,10.90,10.90
1,2011-08-18 12:38:00,0.000000,10.90,10.90,10.90,10.90
2,2011-08-18 12:39:00,0.000000,10.90,10.90,10.90,10.90
3,2011-08-18 12:40:00,0.000000,10.90,10.90,10.90,10.90
4,2011-08-18 12:41:00,0.000000,10.90,10.90,10.90,10.90
...,...,...,...,...,...,...
7246356,2025-05-28 17:13:00,126838.281480,107724.30,107780.40,107721.89,107769.97
7246357,2025-05-28 17:14:00,458533.324113,107769.97,107770.00,107670.30,107670.40
7246358,2025-05-28 17:15:00,295620.940394,107670.40,107689.51,107609.10,107648.51
7246359,2025-05-28 17:16:00,164516.353234,107648.51,107757.90,107641.41,107754.30
7246360,2025-05-28 17:17:00,222803.399635,107754.30,107760.10,107740.70,107742.30

In [6]:
Ob_data

,Unnamed: 0,system_time,midpoint,spread,buys,sells,bids_distance_0,bids_distance_1,bids_distance_2,bids_distance_3,...,asks_market_notional_5,asks_market_notional_6,asks_market_notional_7,asks_market_notional_8,asks_market_notional_9,asks_market_notional_10,asks_market_notional_11,asks_market_notional_12,asks_market_notional_13,asks_market_notional_14
0,0,2021-04-07 11:33:41.122161,55896.285,0.01,4.448599e+06,3.899402e+06,-8.945138e-08,-0.000065,-0.000073,-0.000154,...,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,1176.72998,0.0
1,1,2021-04-07 11:34:41.122161,55948.685,1.43,1.243244e+06,3.606502e+06,-1.277957e-05,-0.000013,-0.000242,-0.000242,...,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.00000,0.0
2,2,2021-04-07 11:35:41.122161,56013.785,0.01,3.069094e+06,1.575759e+06,-8.926374e-08,-0.000009,-0.000070,-0.000088,...,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.00000,0.0
3,3,2021-04-07 11:36:41.122161,55903.575,7.17,1.220819e+06,1.321487e+06,-6.412827e-05,-0.000182,-0.000188,-0.000225,...,0.000000,312.040009,0.0,0.0,0.0,0.0,0.0,0.0,0.00000,0.0
4,4,2021-04-07 11:37:41.122161,55899.995,0.01,2.011287e+06,3.083005e+06,-8.944544e-08,-0.000129,-0.000130,-0.000143,...,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.00000,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17108,17108,2021-04-19 09:50:00.386544,56878.090,6.54,7.205687e+04,1.542092e+05,-5.749138e-05,-0.000058,-0.000068,-0.000094,...,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.00000,0.0
17109,17109,2021-04-19 09:51:00.386544,56944.085,2.57,9.383907e+04,3.085079e+04,-2.256600e-05,-0.000028,-0.000088,-0.000093,...,549.880005,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.00000,0.0
17110,17110,2021-04-19 09:52:00.386544,56873.165,0.01,3.366408e+05,1.198253e+05,-8.791493e-08,-0.000069,-0.000128,-0.000189,...,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.00000,0.0
17111,17111,2021-04-19 09:53:00.386544,56820.445,0.01,3.118859e+04,8.355952e+04,-8.799650e-08,-0.000039,-0.000088,-0.000113,...,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.00000,0.0
17112,17112,2021-04-19 09:54:00.386544,56862.695,2.03,1.471420e+05,4.964134e+04,-1.785002e-05,-0.000030,-0.000119,-0.000136,...,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.00000,0.0

In [7]:
start_time = Ob_data['system_time'].min()
end_time = Ob_data['system_time'].max()
filtered_trading_data = trading_data[
    (trading_data['Open time'] >= start_time) & 
    (trading_data['Open time'] <= end_time)
]

In [8]:
print (Ob_data)
print(Ob_data.columns)
print(filtered_trading_data)
print(filtered_trading_data.columns)

       Unnamed: 0                system_time   midpoint  spread          buys  \
0               0 2021-04-07 11:33:41.122161  55896.285    0.01  4.448599e+06
1               1 2021-04-07 11:34:41.122161  55948.685    1.43  1.243244e+06
2               2 2021-04-07 11:35:41.122161  56013.785    0.01  3.069094e+06
3               3 2021-04-07 11:36:41.122161  55903.575    7.17  1.220819e+06
4               4 2021-04-07 11:37:41.122161  55899.995    0.01  2.011287e+06
...           ...                        ...        ...     ...           ...
17108       17108 2021-04-19 09:50:00.386544  56878.090    6.54  7.205687e+04
17109       17109 2021-04-19 09:51:00.386544  56944.085    2.57  9.383907e+04
17110       17110 2021-04-19 09:52:00.386544  56873.165    0.01  3.366408e+05
17111       17111 2021-04-19 09:53:00.386544  56820.445    0.01  3.118859e+04
17112       17112 2021-04-19 09:54:00.386544  56862.695    2.03  1.471420e+05

              sells  bids_distance_0  bids_distance_1  bids_distance_2  \
0      3.899402e+06    -8.945138e-08        -0.000065        -0.000073
1      3.606502e+06    -1.277957e-05        -0.000013        -0.000242
2      1.575759e+06    -8.926374e-08        -0.000009        -0.000070
3      1.321487e+06    -6.412827e-05        -0.000182        -0.000188
4      3.083005e+06    -8.944544e-08        -0.000129        -0.000130
...             ...              ...              ...              ...
17108  1.542092e+05    -5.749138e-05        -0.000058        -0.000068
17109  3.085079e+04    -2.256600e-05        -0.000028        -0.000088
17110  1.198253e+05    -8.791493e-08        -0.000069        -0.000128
17111  8.355952e+04    -8.799650e-08        -0.000039        -0.000088
17112  4.964134e+04    -1.785002e-05        -0.000030        -0.000119

       bids_distance_3  ...  asks_market_notional_5  asks_market_notional_6  \
0            -0.000154  ...                0.000000                0.000000
1            -0.000242  ...                0.000000                0.000000
2            -0.000088  ...                0.000000                0.000000
3            -0.000225  ...                0.000000              312.040009
4            -0.000143  ...                0.000000                0.000000
...                ...  ...                     ...                     ...
17108        -0.000094  ...                0.000000                0.000000
17109        -0.000093  ...              549.880005                0.000000
17110        -0.000189  ...                0.000000                0.000000
17111        -0.000113  ...                0.000000                0.000000
17112        -0.000136  ...                0.000000                0.000000

       asks_market_notional_7  asks_market_notional_8  asks_market_notional_9  \
0                         0.0                     0.0                     0.0
1                         0.0                     0.0                     0.0
2                         0.0                     0.0                     0.0
3                         0.0                     0.0                     0.0
4                         0.0                     0.0                     0.0
...                       ...                     ...                     ...
17108                     0.0                     0.0                     0.0
17109                     0.0                     0.0                     0.0
17110                     0.0                     0.0                     0.0
17111                     0.0                     0.0                     0.0
17112                     0.0                     0.0                     0.0

       asks_market_notional_10  asks_market_notional_11  \
0                          0.0                      0.0
1                          0.0                      0.0
2                          0.0                      0.0
3                          0.0                      0.0
4                          0.0                      0.0
...                        ...                      ...
17108                      0.0                      0.0
17109                      0.0                      0.0
17110                      0.0                      0.0
17111                      0.0                      0.0
17112                      0.0                      0.0

       asks_market_notional_12  asks_market_notional_13  \
0                          0.0               1176.72998
1                          0.0                  0.00000
2                          0.0                  0.00000
3                          0.0                  0.00000
4                          0.0                  0.00000
...                        ...                      ...
17108                      0.0                  0.00000
17109                      0.0                  0.00000
17110                      0.0                  0.00000
17111                      0.0                  0.00000
17112                      0.0                  0.00000

       asks_market_notional_14
0                          0.0
1                          0.0
2                          0.0
3                          0.0
4                          0.0
...                        ...
17108                      0.0
17109                      0.0
17110                      0.0
17111                      0.0
17112                      0.0

[17113 rows x 156 columns]
Index(['Unnamed: 0', 'system_time', 'midpoint', 'spread', 'buys', 'sells',
       'bids_distance_0', 'bids_distance_1', 'bids_distance_2',
       'bids_distance_3',
       ...
       'asks_market_notional_5', 'asks_market_notional_6',
       'asks_market_notional_7', 'asks_market_notional_8',
       'asks_market_notional_9', 'asks_market_notional_10',
       'asks_market_notional_11', 'asks_market_notional_12',
       'asks_market_notional_13', 'asks_market_notional_14'],
      dtype='object', length=156)
                  Open time        Volume      Open      High       Low  \
5068737 2021-04-07 11:34:00  1.677138e+07  55882.00  56018.50  55861.00
5068738 2021-04-07 11:35:00  1.540796e+07  55881.50  56006.00  55850.00
5068739 2021-04-07 11:36:00  8.846498e+06  56006.00  56075.00  56005.49
5068740 2021-04-07 11:37:00  5.931329e+06  56038.49  56038.50  55881.49
5068741 2021-04-07 11:38:00  2.476139e+07  55882.01  56027.00  55800.50
...                     ...           ...       ...       ...       ...
5085913 2021-04-19 09:50:00  2.774324e+06  56866.50  56907.00  56866.50
5085914 2021-04-19 09:51:00  1.703614e+06  56867.00  56931.50  56866.49
5085915 2021-04-19 09:52:00  3.746203e+06  56930.99  56931.00  56866.50
5085916 2021-04-19 09:53:00  8.690504e+05  56866.50  56866.99  56829.99
5085917 2021-04-19 09:54:00  1.636737e+06  56830.50  56860.00  56829.99

            Close
5068737  55881.50
5068738  56006.00
5068739  56038.49
5068740  55882.01
5068741  56027.00
...           ...
5085913  56867.00
5085914  56930.99
5085915  56866.50
5085916  56830.50
5085917  56859.99

[17181 rows x 6 columns]
Index(['Open time', 'Volume', 'Open', 'High', 'Low', 'Close'], dtype='object')

In [9]:
# If Close>Open : Buy signal 
# If Close<Open : Sell Signal
#
import numpy as np

# Step 1: Floor timestamps to the nearest minute
Ob_data = Ob_data.copy()
Ob_data['minute'] = Ob_data['system_time'].dt.floor('T')

filtered_trading_data = filtered_trading_data.copy()
filtered_trading_data['minute'] = filtered_trading_data['Open time'].dt.floor('T')

# Step 2: Compute midpoint per minute (mean if multiple OB snapshots per minute)
minute_midpoints = Ob_data.groupby('minute')['midpoint'].mean().sort_index()

# Step 3: Compute midpoint drift
midpoint_drift = minute_midpoints.diff()

# Step 4: Join midpoint drift into trading data
filtered_trading_data = filtered_trading_data.merge(
    midpoint_drift.rename('midpoint_drift'), on='minute', how='left'
)

# Step 5: Apply tick rule + midpoint drift to infer trade side
def infer_trade_side(row):
    tick_rule = 'BUY' if row['Close'] > row['Open'] else 'SELL' if row['Close'] < row['Open'] else 'UNKNOWN'
    midpoint_signal = 'BUY' if row['midpoint_drift'] > 0 else 'SELL' if row['midpoint_drift'] < 0 else 'UNKNOWN'

    # Majority vote
    if tick_rule == midpoint_signal:
        return tick_rule
    elif tick_rule != 'UNKNOWN':
        return tick_rule
    elif midpoint_signal != 'UNKNOWN':
        return midpoint_signal
    else:
        return 'UNKNOWN'

# Step 6: Create trade_side column
filtered_trading_data['trade_side'] = filtered_trading_data.apply(infer_trade_side, axis=1)

In [10]:
filtered_trading_data

,Open time,Volume,Open,High,Low,Close,minute,midpoint_drift,trade_side
0,2021-04-07 11:34:00,1.677138e+07,55882.00,56018.50,55861.00,55881.50,2021-04-07 11:34:00,52.400,SELL
1,2021-04-07 11:35:00,1.540796e+07,55881.50,56006.00,55850.00,56006.00,2021-04-07 11:35:00,65.100,BUY
2,2021-04-07 11:36:00,8.846498e+06,56006.00,56075.00,56005.49,56038.49,2021-04-07 11:36:00,-110.210,BUY
3,2021-04-07 11:37:00,5.931329e+06,56038.49,56038.50,55881.49,55882.01,2021-04-07 11:37:00,-3.580,SELL
4,2021-04-07 11:38:00,2.476139e+07,55882.01,56027.00,55800.50,56027.00,2021-04-07 11:38:00,200.180,BUY
...,...,...,...,...,...,...,...,...,...
17176,2021-04-19 09:50:00,2.774324e+06,56866.50,56907.00,56866.50,56867.00,2021-04-19 09:50:00,-16.105,BUY
17177,2021-04-19 09:51:00,1.703614e+06,56867.00,56931.50,56866.49,56930.99,2021-04-19 09:51:00,65.995,BUY
17178,2021-04-19 09:52:00,3.746203e+06,56930.99,56931.00,56866.50,56866.50,2021-04-19 09:52:00,-70.920,SELL
17179,2021-04-19 09:53:00,8.690504e+05,56866.50,56866.99,56829.99,56830.50,2021-04-19 09:53:00,-52.720,SELL
17180,2021-04-19 09:54:00,1.636737e+06,56830.50,56860.00,56829.99,56859.99,2021-04-19 09:54:00,42.250,BUY

In [11]:
Ob_data

,Unnamed: 0,system_time,midpoint,spread,buys,sells,bids_distance_0,bids_distance_1,bids_distance_2,bids_distance_3,...,asks_market_notional_6,asks_market_notional_7,asks_market_notional_8,asks_market_notional_9,asks_market_notional_10,asks_market_notional_11,asks_market_notional_12,asks_market_notional_13,asks_market_notional_14,minute
0,0,2021-04-07 11:33:41.122161,55896.285,0.01,4.448599e+06,3.899402e+06,-8.945138e-08,-0.000065,-0.000073,-0.000154,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,1176.72998,0.0,2021-04-07 11:33:00
1,1,2021-04-07 11:34:41.122161,55948.685,1.43,1.243244e+06,3.606502e+06,-1.277957e-05,-0.000013,-0.000242,-0.000242,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.00000,0.0,2021-04-07 11:34:00
2,2,2021-04-07 11:35:41.122161,56013.785,0.01,3.069094e+06,1.575759e+06,-8.926374e-08,-0.000009,-0.000070,-0.000088,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.00000,0.0,2021-04-07 11:35:00
3,3,2021-04-07 11:36:41.122161,55903.575,7.17,1.220819e+06,1.321487e+06,-6.412827e-05,-0.000182,-0.000188,-0.000225,...,312.040009,0.0,0.0,0.0,0.0,0.0,0.0,0.00000,0.0,2021-04-07 11:36:00
4,4,2021-04-07 11:37:41.122161,55899.995,0.01,2.011287e+06,3.083005e+06,-8.944544e-08,-0.000129,-0.000130,-0.000143,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.00000,0.0,2021-04-07 11:37:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17108,17108,2021-04-19 09:50:00.386544,56878.090,6.54,7.205687e+04,1.542092e+05,-5.749138e-05,-0.000058,-0.000068,-0.000094,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.00000,0.0,2021-04-19 09:50:00
17109,17109,2021-04-19 09:51:00.386544,56944.085,2.57,9.383907e+04,3.085079e+04,-2.256600e-05,-0.000028,-0.000088,-0.000093,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.00000,0.0,2021-04-19 09:51:00
17110,17110,2021-04-19 09:52:00.386544,56873.165,0.01,3.366408e+05,1.198253e+05,-8.791493e-08,-0.000069,-0.000128,-0.000189,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.00000,0.0,2021-04-19 09:52:00
17111,17111,2021-04-19 09:53:00.386544,56820.445,0.01,3.118859e+04,8.355952e+04,-8.799650e-08,-0.000039,-0.000088,-0.000113,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.00000,0.0,2021-04-19 09:53:00
17112,17112,2021-04-19 09:54:00.386544,56862.695,2.03,1.471420e+05,4.964134e+04,-1.785002e-05,-0.000030,-0.000119,-0.000136,...,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.00000,0.0,2021-04-19 09:54:00

In [12]:
filtered_trading_data.drop('midpoint_drift', axis=1)

,Open time,Volume,Open,High,Low,Close,minute,trade_side
0,2021-04-07 11:34:00,1.677138e+07,55882.00,56018.50,55861.00,55881.50,2021-04-07 11:34:00,SELL
1,2021-04-07 11:35:00,1.540796e+07,55881.50,56006.00,55850.00,56006.00,2021-04-07 11:35:00,BUY
2,2021-04-07 11:36:00,8.846498e+06,56006.00,56075.00,56005.49,56038.49,2021-04-07 11:36:00,BUY
3,2021-04-07 11:37:00,5.931329e+06,56038.49,56038.50,55881.49,55882.01,2021-04-07 11:37:00,SELL
4,2021-04-07 11:38:00,2.476139e+07,55882.01,56027.00,55800.50,56027.00,2021-04-07 11:38:00,BUY
...,...,...,...,...,...,...,...,...
17176,2021-04-19 09:50:00,2.774324e+06,56866.50,56907.00,56866.50,56867.00,2021-04-19 09:50:00,BUY
17177,2021-04-19 09:51:00,1.703614e+06,56867.00,56931.50,56866.49,56930.99,2021-04-19 09:51:00,BUY
17178,2021-04-19 09:52:00,3.746203e+06,56930.99,56931.00,56866.50,56866.50,2021-04-19 09:52:00,SELL
17179,2021-04-19 09:53:00,8.690504e+05,56866.50,56866.99,56829.99,56830.50,2021-04-19 09:53:00,SELL
17180,2021-04-19 09:54:00,1.636737e+06,56830.50,56860.00,56829.99,56859.99,2021-04-19 09:54:00,BUY

In [13]:
filtered_trading_data.to_csv('data/trading_data_with_sides.csv', index=False)

Ob_data.to_csv('data/orderbook_data.csv',index=False)